# Generated by Django 4.2.1 on 2023-05-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateTimeField()),
                ('eNodeB_Name', models.CharField(max_length=100)),
                ('Frequency_band', models.IntegerField()),
                ('Cell_FDD_TDD_Indication', models.CharField(max_length=10)),
                ('Cell_Name', models.CharField(max_length=100)),
                ('Downlink_EARFCN', models.IntegerField()),
                ('Downlink_bandwidth', models.CharField(max_length=50)),
                ('LTECell_Tx_and_Rx_Mode', models.CharField(max_length=50)),
                ('LocalCell_Id', models.IntegerField()),
                ('eNodeB_Function_Name', models.CharField(max_length=100)),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('Integrity', models.CharField(max_length=5)),
                ('FT_AVE_4G_LTE_DL_USER_THRPUT_without_Last_TTI', models.FloatField()),
                ('FT_AVERAGE_NB_OF_USERS', models.FloatField()),
                ('FT_PHYSICAL_RESOURCE_BLOCKS_LOAD_DL', models.FloatField()),
                ('FT_PHYSICAL_RESOURCE_BLOCKS_LOAD_UL', models.FloatField()),
                ('FT_4G_LTE_DL_TRAFFIC_VOLUME', models.FloatField()),
                ('FT_4G_LTE_DL_UL_TRAFFIC_VOLUME', models.FloatField()),
                ('FT_4G_LTE_UL_TRAFFIC_VOLUME', models.FloatField()),
                ('AVE_4G_LTE_DL_USER_THRPUT_without_Last_TTI', models.FloatField()),
                ('Average_Nb_of_Used_PRB_for_SRB', models.FloatField()),
                ('Average_Nb_of_PRB_used_per_Ue', models.FloatField()),
                ('Average_Nb_of_e_RAB_per_UE', models.FloatField()),
                ('FT_4G_LTE_CONGESTED_CELLS_RATE', models.CharField(max_length=10)),
                ('FT_4G_LTE_CALL_SETUP_SUCCESS_RATE', models.FloatField()),
                ('FT_4G_LTE_DROP_CALL_RATE_FOR_CARRIER_AGGREGGATION', models.FloatField()),
                ('FT_4G_LTE_DROP_CALL_RATE', models.FloatField()),
                ('FT_4G_LTE_VOLTE_TRAFFIC_VOLUME', models.FloatField()),
                ('FT_CS_FALLBACK_SUCCESS_RATE', models.FloatField()),
                ('FT_CS_FALLBACK_TO_WCDMA_RATIO', models.FloatField()),
                ('FT_S1_SUCCESS_RATE', models.FloatField()),
                ('Average_number_of_activated_UEs', models.FloatField()),
                ('Average_number_of_users_with_data_in_the_buffer', models.FloatField()),
                ('Connected_user_license', models.FloatField()),
                ('Maximum_number_of_activated_UEs', models.IntegerField()),
                ('Maximum_number_of_users_with_data_in_the_buffer', models.FloatField()),
                ('PRBs', models.FloatField()),
                ('PUCCH_and_SRS_resources', models.FloatField()),
                ('RRC_SetupFail', models.IntegerField()),
                ('Service_drop_rate', models.FloatField()),
                ('Service_Integrity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_marketing', models.BooleanField(default=False)),
                ('is_drs', models.BooleanField(default=False)),
                ('is_smc', models.BooleanField(default=False)),
                ('is_client_service', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
